In [1]:
# Data Processing Tools
import numpy as np
import pandas as pd

# Clustering
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from sklearn.utils.testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning

In [34]:
movies = Movie.objects.all()
users = User.objects.all()
profiles = Profile.objects.all()

print(movies.count(), users.count(), profiles.count())

3883 200 200


In [51]:
users_data = np.zeros((users.count(), movies.count()))
print(users_data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [52]:
for user in users:
    for rating in user.profile.ratings.all():
        if rating.movie.id > 3883:
            continue
        users_data[user.id-1][rating.movie.id-1] += rating.rating
        
print(users_data)

[[5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 3. 0. ... 0. 0. 0.]
 [0. 0. 3. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [67]:
import random

def kmeans_custom_clustering_users(k, iters):
    
    # define variables and data
    ml = movies.count()
    ul = users.count()
    clustering_data = [-1]*ul
    
    
    # initialize k of centroids randomly
    centroids = np.zeros((k, ml))   
    for i in range(k):
        for j in range(ml):
            n = random.randrange(1, 6)
            centroids[i][j] += n
            
#     print(centroids)
    
    
    
    for _ in range(iters):
        
        # clustering (find nearest centroid for each movie_data by calculating Euclidean distance)
        for i in range(ul):
            dist = (ml*25)
            cluster = -1
            for j in range(k):
                temp = sum(((users_data[i])-centroids[j])**2)
                print("dist: {}, temp: {}".format(dist, temp))              
                if temp < dist:
                    dist = temp
                    cluster = j

            clustering_data[i] = cluster
        
        
        
        centroids = np.zeros((k, ml))

        # modify each centroid
        cnt_array = [0 for _ in range(k)]
        for i in range(ul):
            user = users_data[i]
            cluster = clustering_data[i]
            cnt_array[cluster] += 1
            centroids[cluster] += user

#             print(cluster, cnt_array)
            
            
        for i in range(k):
            cnt = cnt_array[i]
            for j in range(ml):
                if cnt == 0:
                    centroids[i][j] = 0
                else:
                    centroids[i][j] = round((centroids[i][j] / cnt_array[i]), 4)
            
    
    return clustering_data

In [68]:
clustering_data = kmeans_custom_clustering_users(7, 10)

print(clustering_data)

dist: 97075, temp: 41734.0
dist: 41734.0, temp: 42644.0
dist: 41734.0, temp: 42312.0
dist: 41734.0, temp: 41630.0
dist: 41630.0, temp: 42057.0
dist: 41630.0, temp: 41663.0
dist: 41630.0, temp: 41600.0
dist: 97075, temp: 41266.0
dist: 41266.0, temp: 42202.0
dist: 41266.0, temp: 41764.0
dist: 41266.0, temp: 41006.0
dist: 41006.0, temp: 41359.0
dist: 41006.0, temp: 41347.0
dist: 41006.0, temp: 41114.0
dist: 97075, temp: 41759.0
dist: 41759.0, temp: 42753.0
dist: 41759.0, temp: 42195.0
dist: 41759.0, temp: 41621.0
dist: 41621.0, temp: 41996.0
dist: 41621.0, temp: 41826.0
dist: 41621.0, temp: 41649.0
dist: 97075, temp: 42000.0
dist: 42000.0, temp: 42940.0
dist: 42000.0, temp: 42514.0
dist: 42000.0, temp: 41950.0
dist: 41950.0, temp: 42309.0
dist: 41950.0, temp: 42067.0
dist: 41950.0, temp: 41974.0
dist: 97075, temp: 40489.0
dist: 40489.0, temp: 41339.0
dist: 40489.0, temp: 41089.0
dist: 40489.0, temp: 40471.0
dist: 40471.0, temp: 41148.0
dist: 40471.0, temp: 40700.0
dist: 40471.0, temp: 406

dist: 37283.0, temp: 37855.0
dist: 37283.0, temp: 37237.0
dist: 37237.0, temp: 37444.0
dist: 37237.0, temp: 37094.0
dist: 37094.0, temp: 37251.0
dist: 97075, temp: 41195.0
dist: 41195.0, temp: 42377.0
dist: 41195.0, temp: 41837.0
dist: 41195.0, temp: 41359.0
dist: 41195.0, temp: 41934.0
dist: 41195.0, temp: 41332.0
dist: 41195.0, temp: 41137.0
dist: 97075, temp: 41708.0
dist: 41708.0, temp: 42552.0
dist: 41708.0, temp: 42248.0
dist: 41708.0, temp: 41770.0
dist: 41708.0, temp: 42241.0
dist: 41708.0, temp: 41805.0
dist: 41708.0, temp: 41560.0
dist: 97075, temp: 41878.0
dist: 41878.0, temp: 42780.0
dist: 41878.0, temp: 42374.0
dist: 41878.0, temp: 41720.0
dist: 41720.0, temp: 42197.0
dist: 41720.0, temp: 41797.0
dist: 41720.0, temp: 41684.0
dist: 97075, temp: 41559.0
dist: 41559.0, temp: 42471.0
dist: 41559.0, temp: 42211.0
dist: 41559.0, temp: 41535.0
dist: 41535.0, temp: 41896.0
dist: 41535.0, temp: 41692.0
dist: 41535.0, temp: 41427.0
dist: 97075, temp: 37473.0
dist: 37473.0, temp: 388

dist: 41848.0, temp: 42059.0
dist: 41848.0, temp: 41792.0
dist: 97075, temp: 41409.0
dist: 41409.0, temp: 42279.0
dist: 41409.0, temp: 41967.0
dist: 41409.0, temp: 41341.0
dist: 41341.0, temp: 41784.0
dist: 41341.0, temp: 41532.0
dist: 41341.0, temp: 41357.0
dist: 97075, temp: 41511.0
dist: 41511.0, temp: 42379.0
dist: 41511.0, temp: 42099.0
dist: 41511.0, temp: 41437.0
dist: 41437.0, temp: 41796.0
dist: 41437.0, temp: 41460.0
dist: 41437.0, temp: 41411.0
dist: 97075, temp: 41530.0
dist: 41530.0, temp: 42474.0
dist: 41530.0, temp: 42306.0
dist: 41530.0, temp: 41636.0
dist: 41530.0, temp: 41975.0
dist: 41530.0, temp: 41281.0
dist: 41281.0, temp: 41346.0
dist: 97075, temp: 41060.0
dist: 41060.0, temp: 42222.0
dist: 41060.0, temp: 41852.0
dist: 41060.0, temp: 41254.0
dist: 41060.0, temp: 41685.0
dist: 41060.0, temp: 41193.0
dist: 41060.0, temp: 41092.0
dist: 97075, temp: 41376.0
dist: 41376.0, temp: 42290.0
dist: 41376.0, temp: 41774.0
dist: 41376.0, temp: 41352.0
dist: 41352.0, temp: 416

dist: 41917.0, temp: 42401.0
dist: 41917.0, temp: 41703.0
dist: 41703.0, temp: 42274.0
dist: 41703.0, temp: 41910.0
dist: 41703.0, temp: 41751.0
dist: 97075, temp: 41767.0
dist: 41767.0, temp: 42783.0
dist: 41767.0, temp: 42421.0
dist: 41767.0, temp: 41657.0
dist: 41657.0, temp: 42214.0
dist: 41657.0, temp: 41988.0
dist: 41657.0, temp: 41685.0
dist: 97075, temp: 39183.0
dist: 39183.0, temp: 39949.0
dist: 39183.0, temp: 39437.0
dist: 39183.0, temp: 38815.0
dist: 38815.0, temp: 39460.0
dist: 38815.0, temp: 39158.0
dist: 38815.0, temp: 38497.0
dist: 97075, temp: 40529.0
dist: 40529.0, temp: 41487.0
dist: 40529.0, temp: 41135.0
dist: 40529.0, temp: 40719.0
dist: 40529.0, temp: 41024.0
dist: 40529.0, temp: 40838.0
dist: 40529.0, temp: 40535.0
dist: 97075, temp: 37601.0
dist: 37601.0, temp: 38317.0
dist: 37601.0, temp: 38097.0
dist: 37601.0, temp: 37475.0
dist: 37475.0, temp: 37800.0
dist: 37475.0, temp: 37488.0
dist: 37475.0, temp: 37715.0
dist: 97075, temp: 38064.0
dist: 38064.0, temp: 397

dist: 41008.0, temp: 41299.0
dist: 41008.0, temp: 40804.0
dist: 97075, temp: 41808.0
dist: 41808.0, temp: 42856.0
dist: 41808.0, temp: 42422.0
dist: 41808.0, temp: 41862.0
dist: 41808.0, temp: 42217.0
dist: 41808.0, temp: 41957.0
dist: 41808.0, temp: 41732.0
dist: 97075, temp: 38178.0
dist: 38178.0, temp: 39146.0
dist: 38178.0, temp: 38786.0
dist: 38178.0, temp: 38064.0
dist: 38064.0, temp: 38787.0
dist: 38064.0, temp: 38307.0
dist: 38064.0, temp: 38076.0
dist: 97075, temp: 40323.0
dist: 40323.0, temp: 41229.0
dist: 40323.0, temp: 40745.0
dist: 40323.0, temp: 40169.0
dist: 40169.0, temp: 40902.0
dist: 40169.0, temp: 40358.0
dist: 40169.0, temp: 39925.0
dist: 97075, temp: 41695.0
dist: 41695.0, temp: 42469.0
dist: 41695.0, temp: 42225.0
dist: 41695.0, temp: 41443.0
dist: 41443.0, temp: 41832.0
dist: 41443.0, temp: 41772.0
dist: 41443.0, temp: 41477.0
dist: 97075, temp: 36417.0
dist: 36417.0, temp: 37341.0
dist: 36417.0, temp: 36561.0
dist: 36417.0, temp: 36395.0
dist: 36395.0, temp: 371

dist: 1434.56640625, temp: 1588.0
dist: 1434.56640625, temp: 1588.0
dist: 1434.56640625, temp: 1250.4826032100045
dist: 1250.4826032100045, temp: 1588.0
dist: 1250.4826032100045, temp: 2180.088273940008
dist: 1250.4826032100045, temp: 1256.248207290002
dist: 97075, temp: 1604.56640625
dist: 1604.56640625, temp: 1505.0
dist: 1505.0, temp: 1505.0
dist: 1505.0, temp: 1274.6296032100013
dist: 1274.6296032100013, temp: 1505.0
dist: 1274.6296032100013, temp: 1832.3584739400042
dist: 1274.6296032100013, temp: 1261.4754072899955
dist: 97075, temp: 847.81640625
dist: 847.81640625, temp: 515.0
dist: 515.0, temp: 515.0
dist: 515.0, temp: 592.482003209995
dist: 515.0, temp: 515.0
dist: 515.0, temp: 1772.0000739400052
dist: 515.0, temp: 496.9970072899967
dist: 97075, temp: 2031.56640625
dist: 2031.56640625, temp: 1771.0
dist: 1771.0, temp: 1771.0
dist: 1771.0, temp: 1708.4152032100098
dist: 1708.4152032100098, temp: 1771.0
dist: 1708.4152032100098, temp: 2526.9072739400076
dist: 1708.4152032100098,

dist: 484.0, temp: 484.0
dist: 484.0, temp: 615.6274032099948
dist: 484.0, temp: 484.0
dist: 484.0, temp: 1649.9070739400045
dist: 484.0, temp: 503.72180728999666
dist: 97075, temp: 2114.69140625
dist: 2114.69140625, temp: 2332.0
dist: 2114.69140625, temp: 2332.0
dist: 2114.69140625, temp: 1805.9862032100136
dist: 1805.9862032100136, temp: 2332.0
dist: 1805.9862032100136, temp: 2169.3640739400084
dist: 1805.9862032100136, temp: 1928.0114072900014
dist: 97075, temp: 901.19140625
dist: 901.19140625, temp: 436.0
dist: 436.0, temp: 436.0
dist: 436.0, temp: 576.5196032099952
dist: 436.0, temp: 436.0
dist: 436.0, temp: 1670.2720739400052
dist: 436.0, temp: 452.7136072899967
dist: 97075, temp: 1617.56640625
dist: 1617.56640625, temp: 1223.0
dist: 1223.0, temp: 1223.0
dist: 1223.0, temp: 1296.4846032100027
dist: 1223.0, temp: 1223.0
dist: 1223.0, temp: 2448.5476739400096
dist: 1223.0, temp: 1191.866807289992
dist: 97075, temp: 1218.44140625
dist: 1218.44140625, temp: 1128.0
dist: 1128.0, temp:

dist: 314.0, temp: 314.0
dist: 314.0, temp: 1630.6360739400045
dist: 314.0, temp: 367.54880728999717
dist: 97075, temp: 1262.94140625
dist: 1262.94140625, temp: 1231.0
dist: 1231.0, temp: 1231.0
dist: 1231.0, temp: 1028.8402032099928
dist: 1028.8402032099928, temp: 1231.0
dist: 1028.8402032099928, temp: 1963.4534739400067
dist: 1028.8402032099928, temp: 1037.478407289991
dist: 97075, temp: 1008.56640625
dist: 1008.56640625, temp: 743.0
dist: 743.0, temp: 743.0
dist: 743.0, temp: 675.6998032099931
dist: 675.6998032099931, temp: 743.0
dist: 675.6998032099931, temp: 1447.8148739400042
dist: 675.6998032099931, temp: 613.2852072899917
dist: 97075, temp: 2364.94140625
dist: 2364.94140625, temp: 2294.0
dist: 2294.0, temp: 2294.0
dist: 2294.0, temp: 2040.1686032100142
dist: 2040.1686032100142, temp: 2294.0
dist: 2040.1686032100142, temp: 1948.9948739400056
dist: 1948.9948739400056, temp: 2063.637207290002
dist: 97075, temp: 1593.31640625
dist: 1593.31640625, temp: 1582.0
dist: 1582.0, temp: 15

dist: 1323.5944032100006, temp: 1812.451673940005
dist: 1323.5944032100006, temp: 1352.3384072899958
dist: 97075, temp: 1266.69140625
dist: 1266.69140625, temp: 1082.0
dist: 1082.0, temp: 1082.0
dist: 1082.0, temp: 1002.769003209995
dist: 1002.769003209995, temp: 1082.0
dist: 1002.769003209995, temp: 2016.819273940003
dist: 1002.769003209995, temp: 996.3010072899926
dist: 97075, temp: 3509.06640625
dist: 3509.06640625, temp: 4256.0
dist: 3509.06640625, temp: 4256.0
dist: 3509.06640625, temp: 3702.591403210003
dist: 3509.06640625, temp: 4256.0
dist: 3509.06640625, temp: 4007.732873940002
dist: 3509.06640625, temp: 3650.573807290012
dist: 97075, temp: 2183.06640625
dist: 2183.06640625, temp: 2694.0
dist: 2183.06640625, temp: 2694.0
dist: 2183.06640625, temp: 1973.5920032100169
dist: 1973.5920032100169, temp: 2694.0
dist: 1973.5920032100169, temp: 2668.8218739400027
dist: 1973.5920032100169, temp: 2249.4848072900054
dist: 97075, temp: 1330.94140625
dist: 1330.94140625, temp: 1344.0
dist: 

dist: 424.0, temp: 472.04560728999695
dist: 97075, temp: 5382.69140625
dist: 5382.69140625, temp: 7495.0
dist: 5382.69140625, temp: 7495.0
dist: 5382.69140625, temp: 5700.42160321
dist: 5382.69140625, temp: 7495.0
dist: 5382.69140625, temp: 4303.46627394
dist: 4303.46627394, temp: 6018.846207289959
dist: 97075, temp: 1378.31640625
dist: 1378.31640625, temp: 1487.0
dist: 1378.31640625, temp: 1487.0
dist: 1378.31640625, temp: 1174.8774032099982
dist: 1174.8774032099982, temp: 1487.0
dist: 1174.8774032099982, temp: 2015.8150739400082
dist: 1174.8774032099982, temp: 1172.633407289994
dist: 97075, temp: 966.31640625
dist: 966.31640625, temp: 394.0
dist: 394.0, temp: 394.0
dist: 394.0, temp: 646.3416032099947
dist: 394.0, temp: 394.0
dist: 394.0, temp: 1797.5440739400083
dist: 394.0, temp: 489.8916072899966
dist: 97075, temp: 938.19140625
dist: 938.19140625, temp: 313.0
dist: 313.0, temp: 313.0
dist: 313.0, temp: 616.3424032099947
dist: 313.0, temp: 313.0
dist: 313.0, temp: 1792.544073940005

dist: 97075, temp: 1927.232292140006
dist: 1927.232292140006, temp: 895.6055465599966
dist: 895.6055465599966, temp: 954.0
dist: 895.6055465599966, temp: 1100.7135080999985
dist: 895.6055465599966, temp: 954.0
dist: 895.6055465599966, temp: 2153.435267730014
dist: 895.6055465599966, temp: 836.6290840599987
dist: 97075, temp: 2207.9922921400034
dist: 2207.9922921400034, temp: 1769.2843465600063
dist: 1769.2843465600063, temp: 1906.0
dist: 1769.2843465600063, temp: 1431.038908099988
dist: 1431.038908099988, temp: 1906.0
dist: 1431.038908099988, temp: 2398.344267730021
dist: 1431.038908099988, temp: 1648.0846840600052
dist: 97075, temp: 1842.0400921400048
dist: 1842.0400921400048, temp: 764.9971465599951
dist: 764.9971465599951, temp: 825.0
dist: 764.9971465599951, temp: 934.0973081000077
dist: 764.9971465599951, temp: 825.0
dist: 764.9971465599951, temp: 1967.525867730013
dist: 764.9971465599951, temp: 709.1134840599984
dist: 97075, temp: 1683.1350921400065
dist: 1683.1350921400065, temp

dist: 2591.175746560003, temp: 2699.0
dist: 2591.175746560003, temp: 3468.256067730029
dist: 2591.175746560003, temp: 2327.598884060014
dist: 97075, temp: 4302.803692140006
dist: 4302.803692140006, temp: 5962.500946560002
dist: 4302.803692140006, temp: 6373.0
dist: 4302.803692140006, temp: 4768.679508100003
dist: 4302.803692140006, temp: 6373.0
dist: 4302.803692140006, temp: 3778.3410677300258
dist: 3778.3410677300258, temp: 5396.740084060051
dist: 97075, temp: 2016.5648921400061
dist: 2016.5648921400061, temp: 800.9265465599959
dist: 800.9265465599959, temp: 836.0
dist: 800.9265465599959, temp: 1008.1977081000078
dist: 800.9265465599959, temp: 836.0
dist: 800.9265465599959, temp: 2267.7090677300184
dist: 800.9265465599959, temp: 789.314884059998
dist: 97075, temp: 2256.8492921400043
dist: 2256.8492921400043, temp: 1280.3179465600058
dist: 1280.3179465600058, temp: 1332.0
dist: 1280.3179465600058, temp: 1330.4573080999896
dist: 1280.3179465600058, temp: 1332.0
dist: 1280.3179465600058,

dist: 1039.8895465599953, temp: 983.8252840599985
dist: 97075, temp: 2026.2718921400078
dist: 2026.2718921400078, temp: 1155.4239465600015
dist: 1155.4239465600015, temp: 1192.0
dist: 1155.4239465600015, temp: 1340.5853080999889
dist: 1155.4239465600015, temp: 1192.0
dist: 1155.4239465600015, temp: 2692.8016677300243
dist: 1155.4239465600015, temp: 1162.5164840600032
dist: 97075, temp: 1881.7058921400044
dist: 1881.7058921400044, temp: 689.7517465599977
dist: 689.7517465599977, temp: 820.0
dist: 689.7517465599977, temp: 935.4265081000052
dist: 689.7517465599977, temp: 820.0
dist: 689.7517465599977, temp: 2169.7060677300137
dist: 689.7517465599977, temp: 726.2274840599988
dist: 97075, temp: 1769.2808921400053
dist: 1769.2808921400053, temp: 365.67714655999924
dist: 365.67714655999924, temp: 425.0
dist: 365.67714655999924, temp: 752.2297081000047
dist: 365.67714655999924, temp: 425.0
dist: 365.67714655999924, temp: 2052.345467730013
dist: 365.67714655999924, temp: 473.99828405999835
dist

dist: 97075, temp: 2704.8464921400005
dist: 2704.8464921400005, temp: 1882.5305465600065
dist: 1882.5305465600065, temp: 1996.0
dist: 1882.5305465600065, temp: 1628.581708099984
dist: 1628.581708099984, temp: 1996.0
dist: 1628.581708099984, temp: 2440.6128677300194
dist: 1628.581708099984, temp: 1867.9998840600083
dist: 97075, temp: 1915.9912921400064
dist: 1915.9912921400064, temp: 506.894946559999
dist: 506.894946559999, temp: 568.0
dist: 506.894946559999, temp: 902.7767081000048
dist: 506.894946559999, temp: 568.0
dist: 506.894946559999, temp: 2218.983067730016
dist: 506.894946559999, temp: 608.8816840599995
dist: 97075, temp: 2020.8988921400053
dist: 2020.8988921400053, temp: 1108.2131465599987
dist: 1108.2131465599987, temp: 1173.0
dist: 1108.2131465599987, temp: 1238.7463080999992
dist: 1108.2131465599987, temp: 1173.0
dist: 1108.2131465599987, temp: 2036.7082677300093
dist: 1108.2131465599987, temp: 995.1708840599982
dist: 97075, temp: 1921.3720921400068
dist: 1921.3720921400068

dist: 97075, temp: 2033.134492140006
dist: 2033.134492140006, temp: 1237.283746559999
dist: 1237.283746559999, temp: 1344.0
dist: 1237.283746559999, temp: 1422.326708099994
dist: 1237.283746559999, temp: 1344.0
dist: 1237.283746559999, temp: 2628.709067730021
dist: 1237.283746559999, temp: 1172.9134840599997
dist: 97075, temp: 3050.3256921399993
dist: 3050.3256921399993, temp: 3732.817946559995
dist: 3050.3256921399993, temp: 3939.0
dist: 3050.3256921399993, temp: 3285.522708100012
dist: 3050.3256921399993, temp: 3939.0
dist: 3050.3256921399993, temp: 2671.429667730026
dist: 2671.429667730026, temp: 3283.794884060049
dist: 97075, temp: 2036.752492140007
dist: 2036.752492140007, temp: 811.3915465599947
dist: 811.3915465599947, temp: 852.0
dist: 811.3915465599947, temp: 1135.6829081000033
dist: 811.3915465599947, temp: 852.0
dist: 811.3915465599947, temp: 2407.164267730021
dist: 811.3915465599947, temp: 780.398484059997
dist: 97075, temp: 1773.1814921400069
dist: 1773.1814921400069, temp

dist: 1881.7570921400068, temp: 1317.889746560004
dist: 1317.889746560004, temp: 1487.0
dist: 1317.889746560004, temp: 1314.8755080999936
dist: 1314.8755080999936, temp: 1487.0
dist: 1314.8755080999936, temp: 2131.885067730013
dist: 1314.8755080999936, temp: 1154.1120840599997
dist: 97075, temp: 1769.6102921400054
dist: 1769.6102921400054, temp: 368.21234655999774
dist: 368.21234655999774, temp: 394.0
dist: 368.21234655999774, temp: 804.5831081000069
dist: 368.21234655999774, temp: 394.0
dist: 368.21234655999774, temp: 2165.254667730014
dist: 368.21234655999774, temp: 470.5412840599966
dist: 97075, temp: 1755.9418921400047
dist: 1755.9418921400047, temp: 318.39314655999965
dist: 318.39314655999965, temp: 313.0
dist: 313.0, temp: 774.6165081000061
dist: 313.0, temp: 313.0
dist: 313.0, temp: 2172.893067730014
dist: 313.0, temp: 412.7130840599973
dist: 97075, temp: 6294.594692140012
dist: 6294.594692140012, temp: 8722.10594656
dist: 6294.594692140012, temp: 9061.0
dist: 6294.594692140012,

dist: 97075, temp: 2379.162949610027
dist: 2379.162949610027, temp: 897.1627719299918
dist: 897.1627719299918, temp: 995.4375
dist: 897.1627719299918, temp: 1183.2815052699912
dist: 897.1627719299918, temp: 954.0
dist: 897.1627719299918, temp: 2283.7762809600226
dist: 897.1627719299918, temp: 826.1597711099892
dist: 97075, temp: 2591.1649496100254
dist: 2591.1649496100254, temp: 1748.2417719300106
dist: 1748.2417719300106, temp: 1952.9375
dist: 1748.2417719300106, temp: 1436.242505269986
dist: 1436.242505269986, temp: 1906.0
dist: 1436.242505269986, temp: 2471.230680960024
dist: 1436.242505269986, temp: 1649.9165711100152
dist: 97075, temp: 2292.7525496100257
dist: 2292.7525496100257, temp: 767.1781719299935
dist: 767.1781719299935, temp: 873.4375
dist: 767.1781719299935, temp: 1004.5753052700053
dist: 767.1781719299935, temp: 825.0
dist: 767.1781719299935, temp: 2055.867080960015
dist: 767.1781719299935, temp: 717.8687711099902
dist: 97075, temp: 2156.339949610022
dist: 2156.339949610

dist: 3140.280949610025, temp: 2584.473771930012
dist: 2584.473771930012, temp: 2723.9375
dist: 2584.473771930012, temp: 2783.245105269986
dist: 2584.473771930012, temp: 2699.0
dist: 2584.473771930012, temp: 3552.6882809600324
dist: 2584.473771930012, temp: 2280.4213711100165
dist: 97075, temp: 4442.751349609996
dist: 4442.751349609996, temp: 5874.442971930013
dist: 4442.751349609996, temp: 6248.4375
dist: 4442.751349609996, temp: 4737.986305269997
dist: 4442.751349609996, temp: 6373.0
dist: 4442.751349609996, temp: 3733.04668096003
dist: 3733.04668096003, temp: 5361.834771110037
dist: 97075, temp: 2483.0455496100267
dist: 2483.0455496100267, temp: 809.5015719299914
dist: 809.5015719299914, temp: 903.9375
dist: 809.5015719299914, temp: 1084.2435052699996
dist: 809.5015719299914, temp: 836.0
dist: 809.5015719299914, temp: 2385.3220809600243
dist: 809.5015719299914, temp: 789.9469711099888
dist: 97075, temp: 2730.4571496100257
dist: 2730.4571496100257, temp: 1281.0087719300043
dist: 1281

dist: 1200.0401719299964, temp: 1260.9375
dist: 1200.0401719299964, temp: 1577.8353052699815
dist: 1200.0401719299964, temp: 1223.0
dist: 1200.0401719299964, temp: 2838.5914809600263
dist: 1200.0401719299964, temp: 1166.513771109996
dist: 97075, temp: 2383.6355496100255
dist: 2383.6355496100255, temp: 1033.2527719299949
dist: 1033.2527719299949, temp: 1195.4375
dist: 1033.2527719299949, temp: 1385.723105269991
dist: 1033.2527719299949, temp: 1128.0
dist: 1033.2527719299949, temp: 2449.504080960023
dist: 1033.2527719299949, temp: 987.639371109991
dist: 97075, temp: 2472.929749610026
dist: 2472.929749610026, temp: 1119.4739719299996
dist: 1119.4739719299996, temp: 1279.9375
dist: 1119.4739719299996, temp: 1378.3185052699816
dist: 1119.4739719299996, temp: 1192.0
dist: 1119.4739719299996, temp: 2796.595480960027
dist: 1119.4739719299996, temp: 1210.991171110006
dist: 97075, temp: 2397.988349610027
dist: 2397.988349610027, temp: 644.6379719299966
dist: 644.6379719299966, temp: 846.4375
dis

dist: 232.9375, temp: 463.4541711099974
dist: 97075, temp: 2314.8139496100252
dist: 2314.8139496100252, temp: 1242.6093719300013
dist: 1242.6093719300013, temp: 1450.9375
dist: 1242.6093719300013, temp: 984.3137052700062
dist: 984.3137052700062, temp: 1376.0
dist: 984.3137052700062, temp: 2187.6838809600185
dist: 984.3137052700062, temp: 1188.375171110001
dist: 97075, temp: 2035.1669496100208
dist: 2035.1669496100208, temp: 945.0095719299908
dist: 945.0095719299908, temp: 1141.9375
dist: 945.0095719299908, temp: 932.3143052700054
dist: 932.3143052700054, temp: 1090.0
dist: 932.3143052700054, temp: 1990.4156809600145
dist: 932.3143052700054, temp: 828.4999711099897
dist: 97075, temp: 3592.1589496100314
dist: 3592.1589496100314, temp: 3024.723571930012
dist: 3024.723571930012, temp: 3026.9375
dist: 3024.723571930012, temp: 3319.31950527
dist: 3024.723571930012, temp: 3127.0
dist: 3024.723571930012, temp: 4214.957080960023
dist: 3024.723571930012, temp: 2709.993971110018
dist: 97075, temp

dist: 2028.3543052699763, temp: 2683.0
dist: 2028.3543052699763, temp: 2722.1428809600256
dist: 2028.3543052699763, temp: 2314.1141711100167
dist: 97075, temp: 3154.8685496100275
dist: 3154.8685496100275, temp: 2405.641771930013
dist: 2405.641771930013, temp: 2608.4375
dist: 2405.641771930013, temp: 2092.8723052699866
dist: 2092.8723052699866, temp: 2573.0
dist: 2092.8723052699866, temp: 2169.3222809600093
dist: 2092.8723052699866, temp: 2191.8415711100147
dist: 97075, temp: 2685.4563496100272
dist: 2685.4563496100272, temp: 3483.6123719300017
dist: 2685.4563496100272, temp: 3636.9375
dist: 2685.4563496100272, temp: 3257.618105270005
dist: 2685.4563496100272, temp: 3737.0
dist: 2685.4563496100272, temp: 3674.5952809600335
dist: 2685.4563496100272, temp: 3138.0253711100027
dist: 97075, temp: 2653.809949610025
dist: 2653.809949610025, temp: 1423.5787719300006
dist: 1423.5787719300006, temp: 1530.4375
dist: 1423.5787719300006, temp: 1706.2789052699882
dist: 1423.5787719300006, temp: 1485.

dist: 3007.4567496100244, temp: 2681.3637719300036
dist: 2681.3637719300036, temp: 3034.4375
dist: 2681.3637719300036, temp: 1948.1343052699756
dist: 1948.1343052699756, temp: 3025.0
dist: 1948.1343052699756, temp: 2614.0466809600216
dist: 1948.1343052699756, temp: 2566.878971110012
dist: 97075, temp: 2365.3399496100274
dist: 2365.3399496100274, temp: 480.25657192999705
dist: 480.25657192999705, temp: 547.4375
dist: 480.25657192999705, temp: 979.0207052700057
dist: 480.25657192999705, temp: 485.0
dist: 480.25657192999705, temp: 2346.6866809600233
dist: 480.25657192999705, temp: 577.0381711099946
dist: 97075, temp: 2620.924349610025
dist: 2620.924349610025, temp: 1685.0697719300047
dist: 1685.0697719300047, temp: 1781.9375
dist: 1685.0697719300047, temp: 1938.7609052699834
dist: 1685.0697719300047, temp: 1778.0
dist: 1685.0697719300047, temp: 2646.051880960025
dist: 1685.0697719300047, temp: 1547.8843711100055
dist: 97075, temp: 3706.624349610028
dist: 3706.624349610028, temp: 5519.9853

dist: 460.7003719299967, temp: 526.0
dist: 460.7003719299967, temp: 2247.59728096002
dist: 460.7003719299967, temp: 576.684171109993
dist: 97075, temp: 2501.515149610023
dist: 2501.515149610023, temp: 2070.7337719300162
dist: 2070.7337719300162, temp: 2263.4375
dist: 2070.7337719300162, temp: 2078.3887052699756
dist: 2070.7337719300162, temp: 2266.0
dist: 2070.7337719300162, temp: 2572.0512809600277
dist: 2070.7337719300162, temp: 1829.1429711100172
dist: 97075, temp: 2321.3981496100264
dist: 2321.3981496100264, temp: 361.7445719299975
dist: 361.7445719299975, temp: 459.9375
dist: 361.7445719299975, temp: 834.0211052700064
dist: 361.7445719299975, temp: 372.0
dist: 361.7445719299975, temp: 2267.684680960022
dist: 361.7445719299975, temp: 487.6369711099966
dist: 97075, temp: 3798.808549610039
dist: 3798.808549610039, temp: 5261.010771930015
dist: 3798.808549610039, temp: 5727.4375
dist: 3798.808549610039, temp: 3975.428305269999
dist: 3798.808549610039, temp: 5722.0
dist: 3798.808549610

dist: 4138.6171875, temp: 4295.854758070005
dist: 4138.6171875, temp: 4490.7599999999975
dist: 4138.6171875, temp: 3686.480593429989
dist: 3686.480593429989, temp: 4591.0
dist: 3686.480593429989, temp: 3176.054999999999
dist: 3176.054999999999, temp: 3905.4076734900177
dist: 97075, temp: 3378.6171875
dist: 3378.6171875, temp: 3173.52815807002
dist: 3173.52815807002, temp: 3359.559999999998
dist: 3173.52815807002, temp: 2687.100193429987
dist: 2687.100193429987, temp: 3346.0
dist: 2687.100193429987, temp: 2422.4549999999977
dist: 2422.4549999999977, temp: 2885.068673490015
dist: 97075, temp: 2305.6171875
dist: 2305.6171875, temp: 361.41515806999865
dist: 361.41515806999865, temp: 540.9600000000002
dist: 361.41515806999865, temp: 675.8215934300007
dist: 361.41515806999865, temp: 525.5
dist: 361.41515806999865, temp: 2212.4550000000004
dist: 361.41515806999865, temp: 479.2432734900004
dist: 97075, temp: 2370.3671875
dist: 2370.3671875, temp: 259.41495806999984
dist: 259.41495806999984, te

dist: 538.3515580699988, temp: 641.8756734900015
dist: 97075, temp: 2697.1171875
dist: 2697.1171875, temp: 923.8989580699969
dist: 923.8989580699969, temp: 1157.9599999999994
dist: 923.8989580699969, temp: 962.7535934300047
dist: 923.8989580699969, temp: 1082.0
dist: 923.8989580699969, temp: 2373.654999999998
dist: 923.8989580699969, temp: 1062.1112734900091
dist: 97075, temp: 7834.2421875
dist: 7834.2421875, temp: 12080.531758070078
dist: 7834.2421875, temp: 12425.56
dist: 7834.2421875, temp: 10545.735993430058
dist: 7834.2421875, temp: 12514.0
dist: 7834.2421875, temp: 8808.055000000011
dist: 7834.2421875, temp: 11399.530273490023
dist: 97075, temp: 2382.6171875
dist: 2382.6171875, temp: 676.4113580699985
dist: 676.4113580699985, temp: 798.7600000000001
dist: 676.4113580699985, temp: 1199.029593430001
dist: 676.4113580699985, temp: 741.5
dist: 676.4113580699985, temp: 2566.4549999999967
dist: 676.4113580699985, temp: 701.1100734900036
dist: 97075, temp: 2288.8671875
dist: 2288.867187

dist: 1258.1379580700038, temp: 2595.0549999999967
dist: 1258.1379580700038, temp: 1348.9426734900067
dist: 97075, temp: 2208.3671875
dist: 2208.3671875, temp: 449.9285580699987
dist: 449.9285580699987, temp: 639.96
dist: 449.9285580699987, temp: 708.8931934300028
dist: 449.9285580699987, temp: 607.5
dist: 449.9285580699987, temp: 2042.255000000001
dist: 449.9285580699987, temp: 453.8094734900002
dist: 97075, temp: 2431.6171875
dist: 2431.6171875, temp: 350.2023580699998
dist: 350.2023580699998, temp: 544.9600000000002
dist: 350.2023580699998, temp: 827.7549934300007
dist: 350.2023580699998, temp: 482.5
dist: 350.2023580699998, temp: 2444.5549999999976
dist: 350.2023580699998, temp: 530.0426734899996
dist: 97075, temp: 2706.4921875
dist: 2706.4921875, temp: 856.5289580699971
dist: 856.5289580699971, temp: 1015.9599999999996
dist: 856.5289580699971, temp: 1172.2047934299962
dist: 856.5289580699971, temp: 1011.0
dist: 856.5289580699971, temp: 2616.2549999999974
dist: 856.5289580699971, t

dist: 97075, temp: 5068.9921875
dist: 5068.9921875, temp: 5632.366958069971
dist: 5068.9921875, temp: 5818.360000000001
dist: 5068.9921875, temp: 4729.92859343002
dist: 4729.92859343002, temp: 5938.5
dist: 4729.92859343002, temp: 3404.554999999999
dist: 3404.554999999999, temp: 5189.503073490007
dist: 97075, temp: 3042.1171875
dist: 3042.1171875, temp: 3003.9813580700174
dist: 3003.9813580700174, temp: 3346.959999999999
dist: 3003.9813580700174, temp: 2284.168793429978
dist: 2284.168793429978, temp: 3344.0
dist: 2284.168793429978, temp: 2128.655
dist: 2128.655, temp: 2637.1424734900174
dist: 97075, temp: 3083.3671875
dist: 3083.3671875, temp: 1301.0457580700017
dist: 1301.0457580700017, temp: 1345.5600000000004
dist: 1301.0457580700017, temp: 1681.2389934299888
dist: 1301.0457580700017, temp: 1379.0
dist: 1301.0457580700017, temp: 2832.9550000000004
dist: 1301.0457580700017, temp: 1302.976873490007
dist: 97075, temp: 2104.8671875
dist: 2104.8671875, temp: 786.6551580699967
dist: 786.65

dist: 2376.1171875, temp: 429.8373580699984
dist: 429.8373580699984, temp: 540.7600000000001
dist: 429.8373580699984, temp: 902.2725934300053
dist: 429.8373580699984, temp: 536.5
dist: 429.8373580699984, temp: 2311.8549999999977
dist: 429.8373580699984, temp: 508.8764734900002
dist: 97075, temp: 2508.8671875
dist: 2508.8671875, temp: 416.71735806999953
dist: 416.71735806999953, temp: 568.96
dist: 416.71735806999953, temp: 943.6863934300015
dist: 416.71735806999953, temp: 551.0
dist: 416.71735806999953, temp: 2527.7549999999947
dist: 416.71735806999953, temp: 594.2432734900015
dist: 97075, temp: 2305.3671875
dist: 2305.3671875, temp: 381.11175806999904
dist: 381.11175806999904, temp: 566.5600000000001
dist: 381.11175806999904, temp: 873.6163934300029
dist: 381.11175806999904, temp: 550.0
dist: 381.11175806999904, temp: 2362.4549999999954
dist: 381.11175806999904, temp: 528.176873490001
dist: 97075, temp: 2547.4921875
dist: 2547.4921875, temp: 986.6233580699965
dist: 986.6233580699965, t

dist: 5442.9921875, temp: 7177.5
dist: 5442.9921875, temp: 7183.555000000008
dist: 5442.9921875, temp: 6662.136473490022
dist: 97075, temp: 2563.1171875
dist: 2563.1171875, temp: 702.0173580699985
dist: 702.0173580699985, temp: 884.96
dist: 702.0173580699985, temp: 1102.6505934300037
dist: 702.0173580699985, temp: 866.5
dist: 702.0173580699985, temp: 2572.1549999999957
dist: 702.0173580699985, temp: 849.1442734900046
dist: 97075, temp: 2393.7421875
dist: 2393.7421875, temp: 462.9599580699986
dist: 462.9599580699986, temp: 660.9599999999999
dist: 462.9599580699986, temp: 884.0321934300048
dist: 462.9599580699986, temp: 585.0
dist: 462.9599580699986, temp: 2409.9549999999954
dist: 462.9599580699986, temp: 588.6786734900037
dist: 97075, temp: 2550.9921875
dist: 2550.9921875, temp: 2065.5025580700094
dist: 2065.5025580700094, temp: 2238.96
dist: 2065.5025580700094, temp: 2082.9271934299773
dist: 2065.5025580700094, temp: 2227.5
dist: 2065.5025580700094, temp: 2670.954999999997
dist: 2065.5

dist: 97075, temp: 4138.6171875
dist: 4138.6171875, temp: 4269.648225199994
dist: 4138.6171875, temp: 4490.7599999999975
dist: 4138.6171875, temp: 3662.64292790001
dist: 3662.64292790001, temp: 4591.0
dist: 3662.64292790001, temp: 3176.054999999999
dist: 3176.054999999999, temp: 3929.429352330006
dist: 97075, temp: 3378.6171875
dist: 3378.6171875, temp: 3147.2590252000073
dist: 3147.2590252000073, temp: 3359.559999999998
dist: 3147.2590252000073, temp: 2666.904927900008
dist: 2666.904927900008, temp: 3346.0
dist: 2666.904927900008, temp: 2422.4549999999977
dist: 2422.4549999999977, temp: 2916.2071523300115
dist: 97075, temp: 2305.6171875
dist: 2305.6171875, temp: 357.5296251999991
dist: 357.5296251999991, temp: 540.9600000000002
dist: 357.5296251999991, temp: 670.8427279000006
dist: 357.5296251999991, temp: 525.5
dist: 357.5296251999991, temp: 2212.4550000000004
dist: 357.5296251999991, temp: 502.8027523300033
dist: 97075, temp: 2370.3671875
dist: 2370.3671875, temp: 261.44522519999987

dist: 921.4894252000074, temp: 1157.9599999999994
dist: 921.4894252000074, temp: 957.7773278999986
dist: 921.4894252000074, temp: 1082.0
dist: 921.4894252000074, temp: 2373.654999999998
dist: 921.4894252000074, temp: 1091.0999523299995
dist: 97075, temp: 7834.2421875
dist: 7834.2421875, temp: 12050.439625199975
dist: 7834.2421875, temp: 12425.56
dist: 7834.2421875, temp: 10541.046927900079
dist: 7834.2421875, temp: 12514.0
dist: 7834.2421875, temp: 8808.055000000011
dist: 7834.2421875, temp: 11402.908952329935
dist: 97075, temp: 2382.6171875
dist: 2382.6171875, temp: 682.2782252000009
dist: 682.2782252000009, temp: 798.7600000000001
dist: 682.2782252000009, temp: 1194.3091279000012
dist: 682.2782252000009, temp: 741.5
dist: 682.2782252000009, temp: 2566.4549999999967
dist: 682.2782252000009, temp: 697.5081523300014
dist: 97075, temp: 2288.8671875
dist: 2288.8671875, temp: 410.07962519999825
dist: 410.07962519999825, temp: 530.7600000000002
dist: 410.07962519999825, temp: 734.3765279000

dist: 854.4758252000063, temp: 1175.6455279000043
dist: 854.4758252000063, temp: 1011.0
dist: 854.4758252000063, temp: 2616.2549999999974
dist: 854.4758252000063, temp: 958.8759523299988
dist: 97075, temp: 2350.8671875
dist: 2350.8671875, temp: 585.3614252000011
dist: 585.3614252000011, temp: 799.7599999999996
dist: 585.3614252000011, temp: 758.2409279000007
dist: 585.3614252000011, temp: 742.5
dist: 585.3614252000011, temp: 2130.8550000000014
dist: 585.3614252000011, temp: 652.1361523300008
dist: 97075, temp: 2415.3671875
dist: 2415.3671875, temp: 1195.1942252000051
dist: 1195.1942252000051, temp: 1270.96
dist: 1195.1942252000051, temp: 1498.4411279000094
dist: 1195.1942252000051, temp: 1234.0
dist: 1195.1942252000051, temp: 2688.854999999997
dist: 1195.1942252000051, temp: 1051.0251523299987
dist: 97075, temp: 2325.9921875
dist: 2325.9921875, temp: 295.61542519999966
dist: 295.61542519999966, temp: 401.7600000000001
dist: 295.61542519999966, temp: 749.5783279000012
dist: 295.61542519

dist: 2104.8671875, temp: 784.993025200008
dist: 784.993025200008, temp: 1003.3599999999996
dist: 784.993025200008, temp: 1070.5059279000006
dist: 784.993025200008, temp: 876.0
dist: 784.993025200008, temp: 2322.1549999999997
dist: 784.993025200008, temp: 698.4341523299989
dist: 97075, temp: 2638.9921875
dist: 2638.9921875, temp: 1369.4452252000035
dist: 1369.4452252000035, temp: 1482.1600000000003
dist: 1369.4452252000035, temp: 1448.978927900007
dist: 1369.4452252000035, temp: 1497.0
dist: 1369.4452252000035, temp: 2370.4549999999954
dist: 1369.4452252000035, temp: 1260.100952330005
dist: 97075, temp: 2277.1171875
dist: 2277.1171875, temp: 507.06382519999784
dist: 507.06382519999784, temp: 697.1599999999999
dist: 507.06382519999784, temp: 717.5063279000005
dist: 507.06382519999784, temp: 651.0
dist: 507.06382519999784, temp: 2035.4550000000008
dist: 507.06382519999784, temp: 588.1757523300018
dist: 97075, temp: 4973.2421875
dist: 4973.2421875, temp: 6951.046225199959
dist: 4973.24218

dist: 97075, temp: 2852.1171875
dist: 2852.1171875, temp: 2113.625425200002
dist: 2113.625425200002, temp: 2530.7599999999993
dist: 2113.625425200002, temp: 1464.1767279000078
dist: 1464.1767279000078, temp: 2474.0
dist: 1464.1767279000078, temp: 2202.455
dist: 1464.1767279000078, temp: 2051.654152330015
dist: 97075, temp: 7450.1171875
dist: 7450.1171875, temp: 8741.172025199963
dist: 7450.1171875, temp: 9185.560000000001
dist: 7450.1171875, temp: 7233.843927900057
dist: 7233.843927900057, temp: 9142.5
dist: 7233.843927900057, temp: 5396.255000000003
dist: 5396.255000000003, temp: 8179.318752329999
dist: 97075, temp: 5139.6171875
dist: 5139.6171875, temp: 8802.485225199953
dist: 5139.6171875, temp: 9360.960000000001
dist: 5139.6171875, temp: 7309.711527900076
dist: 5139.6171875, temp: 9346.0
dist: 5139.6171875, temp: 6348.355
dist: 5139.6171875, temp: 8187.2425523300035
dist: 97075, temp: 2605.1171875
dist: 2605.1171875, temp: 3428.3072252000043
dist: 2605.1171875, temp: 3770.359999999

dist: 2581.8549999999973, temp: 3531.0215523300085
dist: 97075, temp: 2464.6171875
dist: 2464.6171875, temp: 1094.4740252000065
dist: 1094.4740252000065, temp: 1401.96
dist: 1094.4740252000065, temp: 1164.9761279000018
dist: 1094.4740252000065, temp: 1376.0
dist: 1094.4740252000065, temp: 2389.0549999999976
dist: 1094.4740252000065, temp: 1084.1703523299998
dist: 97075, temp: 2976.7421875
dist: 2976.7421875, temp: 1759.5766252000024
dist: 1759.5766252000024, temp: 1679.9600000000003
dist: 1679.9600000000003, temp: 2110.1767279000105
dist: 1679.9600000000003, temp: 1901.0
dist: 1679.9600000000003, temp: 3316.054999999999
dist: 1679.9600000000003, temp: 1620.4321523300098
dist: 97075, temp: 2808.1171875
dist: 2808.1171875, temp: 1437.6550252000027
dist: 1437.6550252000027, temp: 1409.96
dist: 1409.96, temp: 1669.7761279000088
dist: 1409.96, temp: 1515.5
dist: 1409.96, temp: 2622.554999999997
dist: 1409.96, temp: 1263.9883523300098
dist: 97075, temp: 2557.4921875
dist: 2557.4921875, temp:

dist: 1758.0459279000127, temp: 3184.5550000000003
dist: 1758.0459279000127, temp: 2064.1744000000085
dist: 97075, temp: 2345.7421875
dist: 2345.7421875, temp: 1298.5265759700105
dist: 1298.5265759700105, temp: 1561.76
dist: 1298.5265759700105, temp: 1191.3767279000028
dist: 1191.3767279000028, temp: 1546.0
dist: 1191.3767279000028, temp: 2456.854999999997
dist: 1191.3767279000028, temp: 1318.2943999999993
dist: 97075, temp: 5248.3671875
dist: 5248.3671875, temp: 6584.54677596998
dist: 5248.3671875, temp: 6860.56
dist: 5248.3671875, temp: 5803.642727900053
dist: 5248.3671875, temp: 6959.0
dist: 5248.3671875, temp: 4135.054999999998
dist: 4135.054999999998, temp: 5798.894400000031
dist: 97075, temp: 2605.7421875
dist: 2605.7421875, temp: 1545.7385759700105
dist: 1545.7385759700105, temp: 1839.5600000000002
dist: 1545.7385759700105, temp: 1665.7741279000086
dist: 1545.7385759700105, temp: 1760.5
dist: 1545.7385759700105, temp: 2733.5549999999976
dist: 1545.7385759700105, temp: 1469.45439

dist: 2573.7683759699994, temp: 2808.6413279000108
dist: 2573.7683759699994, temp: 2740.0
dist: 2573.7683759699994, temp: 3658.355000000001
dist: 2573.7683759699994, temp: 2213.734400000007
dist: 97075, temp: 4481.2421875
dist: 4481.2421875, temp: 5768.350575969983
dist: 4481.2421875, temp: 6215.96
dist: 4481.2421875, temp: 4674.242727900025
dist: 4481.2421875, temp: 6288.0
dist: 4481.2421875, temp: 3727.5550000000007
dist: 3727.5550000000007, temp: 5367.454400000038
dist: 97075, temp: 2565.4921875
dist: 2565.4921875, temp: 816.9759759700128
dist: 816.9759759700128, temp: 942.9599999999995
dist: 816.9759759700128, temp: 1120.1763279000027
dist: 816.9759759700128, temp: 926.0
dist: 816.9759759700128, temp: 2533.654999999997
dist: 816.9759759700128, temp: 786.0544000000034
dist: 97075, temp: 2799.2421875
dist: 2799.2421875, temp: 1283.0575759700107
dist: 1283.0575759700107, temp: 1412.5600000000002
dist: 1283.0575759700107, temp: 1500.176927900008
dist: 1283.0575759700107, temp: 1374.5
d

dist: 4312.7421875, temp: 5602.155000000013
dist: 4312.7421875, temp: 5685.334400000042
dist: 97075, temp: 2669.3671875
dist: 2669.3671875, temp: 1088.4469759700019
dist: 1088.4469759700019, temp: 1354.1600000000003
dist: 1088.4469759700019, temp: 1506.1759279000069
dist: 1088.4469759700019, temp: 1314.5
dist: 1088.4469759700019, temp: 2817.2549999999974
dist: 1088.4469759700019, temp: 1277.1344000000001
dist: 97075, temp: 2377.4921875
dist: 2377.4921875, temp: 403.1381759699982
dist: 403.1381759699982, temp: 586.1600000000003
dist: 403.1381759699982, temp: 788.1087278999998
dist: 403.1381759699982, temp: 527.0
dist: 403.1381759699982, temp: 2295.8549999999987
dist: 403.1381759699982, temp: 571.3744000000019
dist: 97075, temp: 3053.1171875
dist: 3053.1171875, temp: 2085.1855759700084
dist: 2085.1855759700084, temp: 2396.56
dist: 2085.1855759700084, temp: 1643.4435279000083
dist: 1643.4435279000083, temp: 2380.5
dist: 1643.4435279000083, temp: 2567.4549999999954
dist: 1643.4435279000083

dist: 3027.8169759699936, temp: 2977.159999999999
dist: 2977.159999999999, temp: 3326.306727900006
dist: 2977.159999999999, temp: 3117.0
dist: 2977.159999999999, temp: 4331.5549999999985
dist: 2977.159999999999, temp: 2637.5344000000237
dist: 97075, temp: 2274.7421875
dist: 2274.7421875, temp: 280.0701759699973
dist: 280.0701759699973, temp: 439.36000000000007
dist: 280.0701759699973, temp: 692.910727900001
dist: 280.0701759699973, temp: 386.5
dist: 280.0701759699973, temp: 2286.855
dist: 280.0701759699973, temp: 412.49440000000055
dist: 97075, temp: 2421.2421875
dist: 2421.2421875, temp: 1054.6181759700112
dist: 1054.6181759700112, temp: 1301.9599999999996
dist: 1054.6181759700112, temp: 1243.0435279000008
dist: 1054.6181759700112, temp: 1283.5
dist: 1054.6181759700112, temp: 2411.355000000002
dist: 1054.6181759700112, temp: 1021.6544000000027
dist: 97075, temp: 2188.9921875
dist: 2188.9921875, temp: 663.8975759700061
dist: 663.8975759700061, temp: 851.1599999999995
dist: 663.89757597

dist: 2700.6171875, temp: 3690.5
dist: 2700.6171875, temp: 3725.955000000004
dist: 2700.6171875, temp: 3103.5344000000514
dist: 97075, temp: 2720.2421875
dist: 2720.2421875, temp: 1423.8449759700104
dist: 1423.8449759700104, temp: 1565.16
dist: 1423.8449759700104, temp: 1745.5739279000063
dist: 1423.8449759700104, temp: 1561.0
dist: 1423.8449759700104, temp: 2624.3549999999955
dist: 1423.8449759700104, temp: 1288.6144000000018
dist: 97075, temp: 3294.6171875
dist: 3294.6171875, temp: 2395.657975970004
dist: 2395.657975970004, temp: 2731.5599999999986
dist: 2395.657975970004, temp: 2171.2473279000114
dist: 2171.2473279000114, temp: 2647.5
dist: 2171.2473279000114, temp: 3361.6549999999984
dist: 2171.2473279000114, temp: 2418.134400000016
dist: 97075, temp: 2799.4921875
dist: 2799.4921875, temp: 1401.1905759700094
dist: 1401.1905759700094, temp: 1729.3600000000001
dist: 1401.1905759700094, temp: 1102.109127899999
dist: 1102.109127899999, temp: 1712.5
dist: 1102.109127899999, temp: 2256.6

dist: 97075, temp: 3701.2421875
dist: 3701.2421875, temp: 5458.009575969981
dist: 3701.2421875, temp: 5781.560000000001
dist: 3701.2421875, temp: 4782.644127900035
dist: 3701.2421875, temp: 5804.0
dist: 3701.2421875, temp: 4275.755
dist: 3701.2421875, temp: 5005.454400000041
dist: 97075, temp: 2477.9921875
dist: 2477.9921875, temp: 473.93757596999836
dist: 473.93757596999836, temp: 642.5600000000001
dist: 473.93757596999836, temp: 888.7781279000013
dist: 473.93757596999836, temp: 609.5
dist: 473.93757596999836, temp: 2488.254999999994
dist: 473.93757596999836, temp: 660.5344000000017
dist: 97075, temp: 2269.7421875
dist: 2269.7421875, temp: 413.50977596999826
dist: 413.50977596999826, temp: 524.1600000000001
dist: 413.50977596999826, temp: 846.5095279000003
dist: 413.50977596999826, temp: 531.5
dist: 413.50977596999826, temp: 2295.9549999999995
dist: 413.50977596999826, temp: 496.73440000000085
dist: 97075, temp: 4692.7421875
dist: 4692.7421875, temp: 6867.311775969985
dist: 4692.74218

dist: 3358.9763279000053, temp: 4819.0
dist: 3358.9763279000053, temp: 3692.355
dist: 3358.9763279000053, temp: 4220.934400000054
dist: 97075, temp: 2441.9921875
dist: 2441.9921875, temp: 346.13957596999865
dist: 346.13957596999865, temp: 470.3600000000001
dist: 346.13957596999865, temp: 856.7763279000012
dist: 346.13957596999865, temp: 411.0
dist: 346.13957596999865, temp: 2454.854999999995
dist: 346.13957596999865, temp: 509.5744000000007
dist: 97075, temp: 2465.6171875
dist: 2465.6171875, temp: 888.6856359600046
dist: 888.6856359600046, temp: 984.9599999999995
dist: 888.6856359600046, temp: 1211.3761279000043
dist: 888.6856359600046, temp: 971.5
dist: 888.6856359600046, temp: 2416.2549999999956
dist: 888.6856359600046, temp: 837.5705104900043
dist: 97075, temp: 2682.6171875
dist: 2682.6171875, temp: 1705.8410359600055
dist: 1705.8410359600055, temp: 1992.1599999999999
dist: 1705.8410359600055, temp: 1447.5781279000075
dist: 1447.5781279000075, temp: 1949.0
dist: 1447.5781279000075, 

dist: 1411.3052359600058, temp: 1528.5781279000093
dist: 1411.3052359600058, temp: 1620.0
dist: 1411.3052359600058, temp: 2460.454999999995
dist: 1411.3052359600058, temp: 1150.125310490005
dist: 97075, temp: 2573.4921875
dist: 2573.4921875, temp: 1379.4832359600045
dist: 1379.4832359600045, temp: 1584.3600000000001
dist: 1379.4832359600045, temp: 1319.3747279000027
dist: 1319.3747279000027, temp: 1562.0
dist: 1319.3747279000027, temp: 2258.354999999998
dist: 1319.3747279000027, temp: 1331.506310490004
dist: 97075, temp: 2182.6171875
dist: 2182.6171875, temp: 432.91863595999627
dist: 432.91863595999627, temp: 638.7600000000001
dist: 432.91863595999627, temp: 767.1097279000005
dist: 432.91863595999627, temp: 599.5
dist: 432.91863595999627, temp: 2329.3549999999987
dist: 432.91863595999627, temp: 552.6989104900008
dist: 97075, temp: 2973.4921875
dist: 2973.4921875, temp: 1722.2248359600055
dist: 1722.2248359600055, temp: 1845.1600000000003
dist: 1722.2248359600055, temp: 1975.24272790000

dist: 286.35503596, temp: 2429.654999999998
dist: 286.35503596, temp: 493.3573104900009
dist: 97075, temp: 4312.7421875
dist: 4312.7421875, temp: 6366.503235959994
dist: 4312.7421875, temp: 6468.560000000002
dist: 4312.7421875, temp: 5831.641127900038
dist: 4312.7421875, temp: 6614.0
dist: 4312.7421875, temp: 5602.155000000013
dist: 4312.7421875, temp: 5664.7609104899975
dist: 97075, temp: 2669.3671875
dist: 2669.3671875, temp: 1090.9664359599997
dist: 1090.9664359599997, temp: 1354.1600000000003
dist: 1090.9664359599997, temp: 1506.1759279000069
dist: 1090.9664359599997, temp: 1314.5
dist: 1090.9664359599997, temp: 2817.2549999999974
dist: 1090.9664359599997, temp: 1289.1873104900028
dist: 97075, temp: 2377.4921875
dist: 2377.4921875, temp: 403.61163595999795
dist: 403.61163595999795, temp: 586.1600000000003
dist: 403.61163595999795, temp: 788.1087278999998
dist: 403.61163595999795, temp: 527.0
dist: 403.61163595999795, temp: 2295.8549999999987
dist: 403.61163595999795, temp: 585.5275

dist: 3030.84003596001, temp: 2977.159999999999
dist: 2977.159999999999, temp: 3326.306727900006
dist: 2977.159999999999, temp: 3117.0
dist: 2977.159999999999, temp: 4331.5549999999985
dist: 2977.159999999999, temp: 2611.800510489989
dist: 97075, temp: 2274.7421875
dist: 2274.7421875, temp: 281.22603595999834
dist: 281.22603595999834, temp: 439.36000000000007
dist: 281.22603595999834, temp: 692.910727900001
dist: 281.22603595999834, temp: 386.5
dist: 281.22603595999834, temp: 2286.855
dist: 281.22603595999834, temp: 423.2309104900009
dist: 97075, temp: 2421.2421875
dist: 2421.2421875, temp: 1049.8426359600041
dist: 1049.8426359600041, temp: 1301.9599999999996
dist: 1049.8426359600041, temp: 1243.0435279000008
dist: 1049.8426359600041, temp: 1283.5
dist: 1049.8426359600041, temp: 2411.355000000002
dist: 1049.8426359600041, temp: 1031.6731104900039
dist: 97075, temp: 2188.9921875
dist: 2188.9921875, temp: 659.1744359600006
dist: 659.1744359600006, temp: 851.1599999999995
dist: 659.174435

dist: 2377.2421875, temp: 415.9684359599978
dist: 415.9684359599978, temp: 523.3600000000001
dist: 415.9684359599978, temp: 848.0453278999989
dist: 415.9684359599978, temp: 517.5
dist: 415.9684359599978, temp: 2473.454999999996
dist: 415.9684359599978, temp: 569.0185104900012
dist: 97075, temp: 2598.2421875
dist: 2598.2421875, temp: 1048.7878359600043
dist: 1048.7878359600043, temp: 1318.9599999999998
dist: 1048.7878359600043, temp: 1172.5759279000013
dist: 1048.7878359600043, temp: 1305.0
dist: 1048.7878359600043, temp: 2402.054999999997
dist: 1048.7878359600043, temp: 1191.3589104900047
dist: 97075, temp: 2569.8671875
dist: 2569.8671875, temp: 865.127835960004
dist: 865.127835960004, temp: 988.9599999999995
dist: 865.127835960004, temp: 1265.4451279000027
dist: 865.127835960004, temp: 973.5
dist: 865.127835960004, temp: 2776.354999999999
dist: 865.127835960004, temp: 947.0597104900045
dist: 97075, temp: 2745.6171875
dist: 2745.6171875, temp: 2252.764035960006
dist: 2252.764035960006,

dist: 300.5600000000001, temp: 520.8469104900015
dist: 97075, temp: 2377.8671875
dist: 2377.8671875, temp: 419.22743595999856
dist: 419.22743595999856, temp: 623.3600000000001
dist: 419.22743595999856, temp: 854.8411279000005
dist: 419.22743595999856, temp: 570.5
dist: 419.22743595999856, temp: 2358.054999999997
dist: 419.22743595999856, temp: 599.1031104900012
dist: 97075, temp: 2250.9921875
dist: 2250.9921875, temp: 216.71403595999894
dist: 216.71403595999894, temp: 348.36000000000007
dist: 216.71403595999894, temp: 670.0435279000008
dist: 216.71403595999894, temp: 331.5
dist: 216.71403595999894, temp: 2262.155
dist: 216.71403595999894, temp: 365.6357104900008
dist: 97075, temp: 3939.6171875
dist: 3939.6171875, temp: 5693.761835960002
dist: 3939.6171875, temp: 5910.96
dist: 3939.6171875, temp: 5509.175327900038
dist: 3939.6171875, temp: 5995.5
dist: 3939.6171875, temp: 5659.655000000008
dist: 3939.6171875, temp: 5140.720110489984
dist: 97075, temp: 3074.1171875
dist: 3074.1171875, te

dist: 3062.7549999999997, temp: 4813.067310489985
dist: 97075, temp: 3076.4921875
dist: 3076.4921875, temp: 3132.9676359600107
dist: 3076.4921875, temp: 3213.9599999999996
dist: 3076.4921875, temp: 3160.3705279000105
dist: 3076.4921875, temp: 3401.0
dist: 3076.4921875, temp: 3749.855000000002
dist: 3076.4921875, temp: 2650.2313104899868
dist: 97075, temp: 2816.7421875
dist: 2816.7421875, temp: 964.2784359600025
dist: 964.2784359600025, temp: 1082.7599999999995
dist: 964.2784359600025, temp: 1324.1773279000035
dist: 964.2784359600025, temp: 1079.0
dist: 964.2784359600025, temp: 2659.454999999997
dist: 964.2784359600025, temp: 1018.8683104900047
dist: 97075, temp: 9104.2421875
dist: 9104.2421875, temp: 12232.737835960059
dist: 9104.2421875, temp: 12649.160000000002
dist: 9104.2421875, temp: 10798.982527900085
dist: 9104.2421875, temp: 12758.0
dist: 9104.2421875, temp: 8362.054999999998
dist: 8362.054999999998, temp: 11604.267310490046
dist: 97075, temp: 2161.2421875
dist: 2161.2421875, t

dist: 97075, temp: 4040.3671875
dist: 4040.3671875, temp: 3719.763635960009
dist: 3719.763635960009, temp: 3971.3599999999988
dist: 3719.763635960009, temp: 3227.591747330007
dist: 3227.591747330007, temp: 3937.5
dist: 3227.591747330007, temp: 3744.454999999999
dist: 3227.591747330007, temp: 3498.330706809974
dist: 97075, temp: 2533.8671875
dist: 2533.8671875, temp: 1261.8410359600066
dist: 1261.8410359600066, temp: 1186.1599999999996
dist: 1186.1599999999996, temp: 1626.7563473299867
dist: 1186.1599999999996, temp: 1381.0
dist: 1186.1599999999996, temp: 2834.8549999999987
dist: 1186.1599999999996, temp: 1084.6377068100078
dist: 97075, temp: 2236.9921875
dist: 2236.9921875, temp: 1411.3052359600058
dist: 1411.3052359600058, temp: 1588.16
dist: 1411.3052359600058, temp: 1518.8215473299895
dist: 1411.3052359600058, temp: 1620.0
dist: 1411.3052359600058, temp: 2460.454999999995
dist: 1411.3052359600058, temp: 1150.288706810014
dist: 97075, temp: 2573.4921875
dist: 2573.4921875, temp: 1379

dist: 2537.223635960008, temp: 3492.3549999999987
dist: 2537.223635960008, temp: 2061.764906810034
dist: 97075, temp: 2759.3671875
dist: 2759.3671875, temp: 908.1506359600033
dist: 908.1506359600033, temp: 1040.3599999999997
dist: 908.1506359600033, temp: 1118.596547329997
dist: 908.1506359600033, temp: 1032.0
dist: 908.1506359600033, temp: 2549.354999999995
dist: 908.1506359600033, temp: 1045.681706810007
dist: 97075, temp: 2442.8671875
dist: 2442.8671875, temp: 286.35503596
dist: 286.35503596, temp: 416.9599999999999
dist: 286.35503596, temp: 764.4331473300034
dist: 286.35503596, temp: 384.5
dist: 286.35503596, temp: 2429.654999999998
dist: 286.35503596, temp: 495.63870680999787
dist: 97075, temp: 4312.7421875
dist: 4312.7421875, temp: 6366.503235959994
dist: 4312.7421875, temp: 6468.560000000002
dist: 4312.7421875, temp: 5824.883947329974
dist: 4312.7421875, temp: 6614.0
dist: 4312.7421875, temp: 5602.155000000013
dist: 4312.7421875, temp: 5667.506106809983
dist: 97075, temp: 2669.3

dist: 1645.9807473299913, temp: 2126.2011068100214
dist: 97075, temp: 2392.2421875
dist: 2392.2421875, temp: 365.40603595999835
dist: 365.40603595999835, temp: 305.3600000000002
dist: 305.3600000000002, temp: 868.0467473300042
dist: 305.3600000000002, temp: 401.5
dist: 305.3600000000002, temp: 2433.254999999996
dist: 305.3600000000002, temp: 503.63910680999555
dist: 97075, temp: 2422.9921875
dist: 2422.9921875, temp: 1198.508635960004
dist: 1198.508635960004, temp: 1492.5600000000002
dist: 1198.508635960004, temp: 999.2761473300053
dist: 999.2761473300053, temp: 1361.5
dist: 999.2761473300053, temp: 2323.254999999999
dist: 999.2761473300053, temp: 1268.0727068100168
dist: 97075, temp: 2129.4921875
dist: 2129.4921875, temp: 902.3014359600052
dist: 902.3014359600052, temp: 1161.3599999999997
dist: 902.3014359600052, temp: 949.787947330005
dist: 902.3014359600052, temp: 1132.5
dist: 902.3014359600052, temp: 2110.655000000001
dist: 902.3014359600052, temp: 869.9853068099989
dist: 97075, te

dist: 2745.6171875, temp: 2252.764035960006
dist: 2252.764035960006, temp: 2690.759999999999
dist: 2252.764035960006, temp: 1718.5973473299894
dist: 1718.5973473299894, temp: 2629.0
dist: 1718.5973473299894, temp: 2659.154999999998
dist: 1718.5973473299894, temp: 2256.0701068100198
dist: 97075, temp: 2414.1171875
dist: 2414.1171875, temp: 410.02203595999845
dist: 410.02203595999845, temp: 544.1600000000001
dist: 410.02203595999845, temp: 878.2393473300035
dist: 410.02203595999845, temp: 537.5
dist: 410.02203595999845, temp: 2427.7549999999956
dist: 410.02203595999845, temp: 555.7697068099964
dist: 97075, temp: 2971.4921875
dist: 2971.4921875, temp: 2414.2012359600126
dist: 2414.2012359600126, temp: 2658.3599999999983
dist: 2414.2012359600126, temp: 1952.4043473299894
dist: 1952.4043473299894, temp: 2713.0
dist: 1952.4043473299894, temp: 2875.7549999999983
dist: 1952.4043473299894, temp: 2418.596106809994
dist: 97075, temp: 3257.2421875
dist: 3257.2421875, temp: 2309.510835960004
dist: 

dist: 3074.1171875, temp: 1639.7944359600065
dist: 1639.7944359600065, temp: 1925.3600000000004
dist: 1639.7944359600065, temp: 1405.7261473299952
dist: 1405.7261473299952, temp: 1940.5
dist: 1405.7261473299952, temp: 2560.5549999999967
dist: 1405.7261473299952, temp: 1768.5949068100265
dist: 97075, temp: 3084.4921875
dist: 3084.4921875, temp: 2596.274635960008
dist: 2596.274635960008, temp: 3041.5599999999986
dist: 2596.274635960008, temp: 1996.0769473299888
dist: 1996.0769473299888, temp: 2944.0
dist: 1996.0769473299888, temp: 2698.7549999999983
dist: 1996.0769473299888, temp: 2671.067106809991
dist: 97075, temp: 2459.4921875
dist: 2459.4921875, temp: 500.94423595999757
dist: 500.94423595999757, temp: 599.5600000000002
dist: 500.94423595999757, temp: 974.2087473300046
dist: 500.94423595999757, temp: 562.0
dist: 500.94423595999757, temp: 2518.354999999996
dist: 500.94423595999757, temp: 608.8139068099953
dist: 97075, temp: 2732.7421875
dist: 2732.7421875, temp: 1663.8652359600053
dist

dist: 97075, temp: 2161.2421875
dist: 2161.2421875, temp: 441.2760359599958
dist: 441.2760359599958, temp: 568.7600000000002
dist: 441.2760359599958, temp: 838.0149473300052
dist: 441.2760359599958, temp: 556.5
dist: 441.2760359599958, temp: 2373.9549999999954
dist: 441.2760359599958, temp: 533.637506809995
dist: 97075, temp: 2229.1171875
dist: 2229.1171875, temp: 341.4304359599981
dist: 341.4304359599981, temp: 485.9600000000002
dist: 341.4304359599981, temp: 749.368147330004
dist: 341.4304359599981, temp: 458.5
dist: 341.4304359599981, temp: 2307.554999999999
dist: 341.4304359599981, temp: 466.3335068099948
dist: 97075, temp: 4468.1171875
dist: 4468.1171875, temp: 5140.584235960006
dist: 4468.1171875, temp: 5514.16
dist: 4468.1171875, temp: 4169.790947330007
dist: 4169.790947330007, temp: 5566.0
dist: 4169.790947330007, temp: 2776.1549999999984
dist: 2776.1549999999984, temp: 4740.2449068099795
dist: 97075, temp: 4133.9921875
dist: 4133.9921875, temp: 4395.581835960017
dist: 4133.992

dist: 3717.478125000004, temp: 3971.3599999999988
dist: 3717.478125000004, temp: 3227.591747330007
dist: 3227.591747330007, temp: 3937.5
dist: 3227.591747330007, temp: 3744.454999999999
dist: 3227.591747330007, temp: 3493.9840908699916
dist: 97075, temp: 2533.8671875
dist: 2533.8671875, temp: 1258.9281249999997
dist: 1258.9281249999997, temp: 1186.1599999999996
dist: 1186.1599999999996, temp: 1626.7563473299867
dist: 1186.1599999999996, temp: 1381.0
dist: 1186.1599999999996, temp: 2834.8549999999987
dist: 1186.1599999999996, temp: 1083.4442908699955
dist: 97075, temp: 2236.9921875
dist: 2236.9921875, temp: 1404.7281249999987
dist: 1404.7281249999987, temp: 1588.16
dist: 1404.7281249999987, temp: 1518.8215473299895
dist: 1404.7281249999987, temp: 1620.0
dist: 1404.7281249999987, temp: 2460.454999999995
dist: 1404.7281249999987, temp: 1151.9414908699953
dist: 97075, temp: 2573.4921875
dist: 2573.4921875, temp: 1369.1531250000005
dist: 1369.1531250000005, temp: 1584.3600000000001
dist: 13

dist: 97075, temp: 2759.3671875
dist: 2759.3671875, temp: 907.0281249999999
dist: 907.0281249999999, temp: 1040.3599999999997
dist: 907.0281249999999, temp: 1118.596547329997
dist: 907.0281249999999, temp: 1032.0
dist: 907.0281249999999, temp: 2549.354999999995
dist: 907.0281249999999, temp: 1055.532290869997
dist: 97075, temp: 2442.8671875
dist: 2442.8671875, temp: 287.95312500000006
dist: 287.95312500000006, temp: 416.9599999999999
dist: 287.95312500000006, temp: 764.4331473300034
dist: 287.95312500000006, temp: 384.5
dist: 287.95312500000006, temp: 2429.654999999998
dist: 287.95312500000006, temp: 503.8078908699981
dist: 97075, temp: 4312.7421875
dist: 4312.7421875, temp: 6354.778124999998
dist: 4312.7421875, temp: 6468.560000000002
dist: 4312.7421875, temp: 5824.883947329974
dist: 4312.7421875, temp: 6614.0
dist: 4312.7421875, temp: 5602.155000000013
dist: 4312.7421875, temp: 5658.628490869982
dist: 97075, temp: 2669.3671875
dist: 2669.3671875, temp: 1095.5531250000001
dist: 1095.5

dist: 1645.9807473299913, temp: 2140.355
dist: 1645.9807473299913, temp: 2149.218690869997
dist: 97075, temp: 2392.2421875
dist: 2392.2421875, temp: 366.22812500000003
dist: 366.22812500000003, temp: 305.3600000000002
dist: 305.3600000000002, temp: 868.0467473300042
dist: 305.3600000000002, temp: 401.5
dist: 305.3600000000002, temp: 2433.254999999996
dist: 305.3600000000002, temp: 509.9900908700017
dist: 97075, temp: 2422.9921875
dist: 2422.9921875, temp: 1195.5281250000005
dist: 1195.5281250000005, temp: 1492.5600000000002
dist: 1195.5281250000005, temp: 999.2761473300053
dist: 999.2761473300053, temp: 1361.5
dist: 999.2761473300053, temp: 2323.254999999999
dist: 999.2761473300053, temp: 1278.2146908699967
dist: 97075, temp: 2129.4921875
dist: 2129.4921875, temp: 899.0531249999998
dist: 899.0531249999998, temp: 1161.3599999999997
dist: 899.0531249999998, temp: 949.787947330005
dist: 899.0531249999998, temp: 1132.5
dist: 899.0531249999998, temp: 2110.655000000001
dist: 899.053124999999

dist: 2971.4921875, temp: 2406.003125000004
dist: 2406.003125000004, temp: 2658.3599999999983
dist: 2406.003125000004, temp: 1952.4043473299894
dist: 1952.4043473299894, temp: 2713.0
dist: 1952.4043473299894, temp: 2875.7549999999983
dist: 1952.4043473299894, temp: 2435.263890869994
dist: 97075, temp: 3257.2421875
dist: 3257.2421875, temp: 2300.0031249999984
dist: 2300.0031249999984, temp: 2647.9599999999996
dist: 2300.0031249999984, temp: 1805.1745473299934
dist: 1805.1745473299934, temp: 2602.5
dist: 1805.1745473299934, temp: 2464.954999999999
dist: 1805.1745473299934, temp: 2391.7636908699974
dist: 97075, temp: 2700.6171875
dist: 2700.6171875, temp: 3419.028125000005
dist: 2700.6171875, temp: 3641.1599999999985
dist: 2700.6171875, temp: 3276.4019473300123
dist: 2700.6171875, temp: 3690.5
dist: 2700.6171875, temp: 3725.955000000004
dist: 2700.6171875, temp: 3107.812690869986
dist: 97075, temp: 2720.2421875
dist: 2720.2421875, temp: 1417.3281249999995
dist: 1417.3281249999995, temp: 1

dist: 2595.953125000002, temp: 3041.5599999999986
dist: 2595.953125000002, temp: 1996.0769473299888
dist: 1996.0769473299888, temp: 2944.0
dist: 1996.0769473299888, temp: 2698.7549999999983
dist: 1996.0769473299888, temp: 2676.625490869995
dist: 97075, temp: 2459.4921875
dist: 2459.4921875, temp: 502.05312500000036
dist: 502.05312500000036, temp: 599.5600000000002
dist: 502.05312500000036, temp: 974.2087473300046
dist: 502.05312500000036, temp: 562.0
dist: 502.05312500000036, temp: 2518.354999999996
dist: 502.05312500000036, temp: 613.2616908700016
dist: 97075, temp: 2732.7421875
dist: 2732.7421875, temp: 1658.1531249999991
dist: 1658.1531249999991, temp: 1829.76
dist: 1658.1531249999991, temp: 1872.2397473299918
dist: 1658.1531249999991, temp: 1828.0
dist: 1658.1531249999991, temp: 2784.9549999999977
dist: 1658.1531249999991, temp: 1566.7632908699954
dist: 97075, temp: 3701.2421875
dist: 3701.2421875, temp: 5429.278124999996
dist: 3701.2421875, temp: 5781.560000000001
dist: 3701.24218

dist: 340.65312500000016, temp: 2307.554999999999
dist: 340.65312500000016, temp: 474.9886908700038
dist: 97075, temp: 4468.1171875
dist: 4468.1171875, temp: 5130.428125000003
dist: 4468.1171875, temp: 5514.16
dist: 4468.1171875, temp: 4169.790947330007
dist: 4169.790947330007, temp: 5566.0
dist: 4169.790947330007, temp: 2776.1549999999984
dist: 2776.1549999999984, temp: 4742.085090869997
dist: 97075, temp: 4133.9921875
dist: 4133.9921875, temp: 4384.728124999999
dist: 4133.9921875, temp: 4861.159999999999
dist: 4133.9921875, temp: 3371.3143473300142
dist: 3371.3143473300142, temp: 4819.0
dist: 3371.3143473300142, temp: 3692.355
dist: 3371.3143473300142, temp: 4279.398690869984
dist: 97075, temp: 2441.9921875
dist: 2441.9921875, temp: 352.378125
dist: 352.378125, temp: 470.3600000000001
dist: 352.378125, temp: 846.8527473300047
dist: 352.378125, temp: 411.0
dist: 352.378125, temp: 2454.854999999995
dist: 352.378125, temp: 523.853090870002
[6, 3, 6, 1, 3, 6, 1, 3, 3, 5, 6, 4, 3, 1, 3, 4

In [8]:
def user_clustering(method, k):

    # K-Means
    if method == 'km':
        model = KMeans(n_clusters=k, init="random", random_state=0)
        model.fit(users_data)
        clustering_data = model.predict(users_data)

    # Hierarchy
    if method == 'hr':
        model = AgglomerativeClustering(n_clusters=k, affinity="euclidean", linkage='ward')
        clustering_data = model.fit_predict(users_data)

    # EM
    if method == 'em':
        model = GaussianMixture(n_components=k, init_params='random', random_state=0, max_iter=100)
        with ignore_warnings(category=ConvergenceWarning):
            model.fit(users_data)
        clustering_data = model.predict(users_data)
    
    return clustering_data

In [53]:
kmeans_data = user_clustering('km', 7)
kmeans_data

array([1, 0, 1, 1, 4, 1, 1, 1, 1, 3, 1, 1, 0, 1, 0, 1, 3, 0, 0, 1, 1, 0,
       3, 4, 1, 0, 1, 4, 0, 1, 1, 1, 4, 4, 4, 0, 1, 1, 1, 1, 1, 3, 1, 0,
       4, 1, 1, 6, 0, 1, 1, 1, 5, 1, 1, 1, 1, 3, 4, 1, 1, 4, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 4, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 6, 1, 1, 1, 0, 1, 0, 0, 4, 1,
       4, 0, 1, 4, 0, 1, 3, 1, 1, 1, 1, 1, 1, 4, 0, 6, 2, 4, 0, 1, 1, 1,
       1, 4, 0, 1, 1, 1, 2, 0, 0, 1, 1, 5, 1, 1, 6, 1, 1, 1, 2, 0, 4, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 4, 1, 1, 4, 1, 0, 4, 1, 2, 1, 1, 0,
       0, 1])

In [54]:
hr_data = user_clustering('hr', 7)
hr_data

array([6, 4, 6, 6, 4, 6, 4, 4, 6, 1, 6, 6, 6, 6, 4, 6, 4, 1, 1, 6, 6, 1,
       4, 6, 6, 4, 6, 6, 4, 6, 6, 6, 0, 6, 6, 1, 6, 6, 6, 6, 6, 4, 6, 1,
       4, 6, 6, 1, 4, 6, 6, 4, 5, 6, 6, 6, 6, 1, 6, 6, 6, 0, 6, 6, 4, 6,
       6, 6, 6, 6, 6, 6, 1, 6, 1, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6,
       6, 4, 6, 1, 4, 6, 4, 6, 6, 6, 6, 6, 4, 6, 4, 6, 4, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 1, 4, 6, 6, 6, 6, 0, 6, 4, 6, 4, 6, 4, 4, 6, 6,
       6, 4, 6, 0, 4, 6, 1, 6, 6, 6, 4, 6, 6, 0, 4, 1, 2, 0, 1, 6, 6, 6,
       6, 4, 1, 6, 6, 6, 0, 4, 4, 6, 6, 0, 6, 6, 1, 6, 6, 6, 0, 4, 0, 6,
       6, 6, 6, 6, 1, 6, 6, 6, 4, 6, 2, 6, 6, 6, 6, 1, 6, 6, 3, 6, 6, 1,
       1, 6], dtype=int64)

In [55]:
em_data = user_clustering('em', 7)
em_data

array([1, 1, 6, 6, 3, 3, 3, 3, 6, 5, 2, 6, 5, 2, 5, 4, 6, 3, 2, 5, 3, 2,
       1, 3, 6, 2, 2, 4, 5, 6, 0, 2, 1, 1, 2, 6, 2, 4, 4, 2, 6, 5, 5, 0,
       2, 3, 5, 5, 2, 6, 5, 2, 4, 6, 4, 1, 3, 2, 2, 6, 1, 1, 4, 1, 3, 4,
       6, 5, 2, 5, 2, 6, 1, 1, 1, 2, 5, 5, 1, 6, 2, 2, 5, 3, 1, 0, 2, 3,
       3, 1, 5, 5, 4, 3, 1, 3, 2, 4, 2, 6, 0, 2, 5, 6, 0, 6, 6, 3, 4, 3,
       4, 5, 6, 3, 6, 1, 1, 6, 1, 3, 5, 3, 6, 4, 2, 3, 1, 0, 0, 2, 2, 6,
       6, 4, 1, 6, 6, 0, 3, 1, 4, 2, 3, 4, 1, 4, 1, 3, 6, 6, 4, 1, 3, 6,
       5, 3, 5, 5, 2, 5, 5, 5, 2, 2, 6, 0, 1, 5, 2, 5, 1, 5, 3, 1, 3, 2,
       4, 3, 2, 0, 5, 1, 2, 4, 3, 3, 3, 5, 3, 3, 2, 6, 1, 2, 3, 1, 0, 3,
       0, 1], dtype=int64)

In [30]:
for i in range(users.count()):
    user = users[i]
    user.profile.cluster = kmeans_data[i]
    user.profile.save()

In [41]:
related_profiles = profiles.filter(cluster__exact=3)
for profile in related_profiles:
    print(profile.user.username)

user10
user17
user23
user42
user58
user117
user139
