In [1]:
import numpy as np

In [3]:
mat1 = np.array(([1,2,3], [4,5,6], [7,8,9]))
mat2 = np.array(([9,8,7], [6,5,4], [3,2,1]))

print(mat1, mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
mat3 = np.add(mat1, mat2)
mat3

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [5]:
mat4 = mat1*mat2
mat4

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [6]:
mat5 =mat1.T
mat5

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
mat6 = np.array(([1,2,3], [4,5,6]))
mat6

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
mat7 = mat6.T
mat7

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.random.randint(5, size=(3,2))

array([[4, 1],
       [4, 1],
       [4, 3]])

In [15]:
def divide(a, b):
    return round(a/b, 4)

In [16]:
div = np.vectorize(divide)
mat8 = div(mat5, 2)
mat8

array([[0.5, 2. , 3.5],
       [1. , 2.5, 4. ],
       [1.5, 3. , 4.5]])

In [17]:
mat10 = np.full((1, 5), 1)
mat10

array([[1, 1, 1, 1, 1]])